# Level 1-Task 1-Task: Top Cuisines

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('Dataset.csv')
df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [ ]:
print("Info :",df.info(), "\n")
print("Shape :",df.shape, "\n")
print("Describe :",df.describe(), "\n")
print("Columns : ",df.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB
Info : None

Shape : (9551, 21)

Describe :        Restaurant ID  Country Code    Longitude     Latitude  \
count   9.551000e+03   9551.000000  9551.000000  9551.000000
mean    9.051128e+06     18.365616    64.126574    25.854381
std     8.791521e+06     56.750546    41.467058    11.007935
min     5.300000e+01      1.000000  -157.948486   -41.330428
25%     3.019625e+05      1.000000    77.081343    28.478713
50%     6.004089e+06      1.000000    77.191964    28.570469
75%     1.835229e+07      1.000000    77.282006    28.642758
max     1.850065e+07    216.000000   174.832089    55.976980

       Average Cost for two  Price range  Aggregate rating         Votes
count           9551.000000  9551.000000       9551.000000   9551.000000
mean            1199.210763     1.804837          2.666370    156.909748
std            16121.183073     0.905609          1.516378    430.169145
min                0.000000     1.000000          0.000000      0.000000
25%              250.000000     1.000000          2.500000      5.000000
50%              400.000000     2.000000          3.200000     31.000000
75%              700.000000     2.000000          3.700000    131.000000
max           800000.000000     4.000000          4.900000  10934.000000

Columns :  Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [ ]:
df.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
df['Cuisines'].dtype

dtype('O')

In [ ]:
df['Cuisines'].isna().sum()

np.int64(9)

In [ ]:
df['Cuisines'].isna().any()

np.True_

In [ ]:
top = df['Cuisines'].value_counts().head(20)
top

Cuisines
North Indian                      936
North Indian, Chinese             511
Chinese                           354
Fast Food                         354
North Indian, Mughlai             334
Cafe                              299
Bakery                            218
North Indian, Mughlai, Chinese    197
Bakery, Desserts                  170
Street Food                       149
Pizza, Fast Food                  131
Chinese, Fast Food                118
Mithai, Street Food               116
South Indian                      112
Bakery, Fast Food                 108
Chinese, North Indian             105
Mughlai                           103
Ice Cream, Desserts                83
Ice Cream                          74
North Indian, Fast Food            74
Name: count, dtype: int64

In [ ]:
df.loc[[577,10], 'Cuisines']

577    Lebanese, Arabian, Middle Eastern
10                     Filipino, Mexican
Name: Cuisines, dtype: object

In [ ]:
print(df['Cuisines'].head(20))

0             French, Japanese, Desserts
1                               Japanese
2       Seafood, Asian, Filipino, Indian
3                        Japanese, Sushi
4                       Japanese, Korean
5                                Chinese
6                        Asian, European
7     Seafood, Filipino, Asian, European
8                European, Asian, Indian
9                               Filipino
10                     Filipino, Mexican
11         American, Ice Cream, Desserts
12                     Filipino, Mexican
13                              Filipino
14                                Korean
15     Cafe, American, Italian, Filipino
16                        Italian, Pizza
17                              Filipino
18                Cafe, Korean, Desserts
19       Cafe, Bakery, American, Italian
Name: Cuisines, dtype: object

In [ ]:
df[df['Cuisines'].isna()]

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
84,17284105,Cookie Shoppe,216,Albany,"115 N Jackson St, Albany, GA 31701",Albany,"Albany, Albany",-84.154000,31.577200,NaN,...,Dollar($),No,No,No,No,1,3.4,Orange,Average,34
87,17284211,Pearly's Famous Country Cookng,216,Albany,"814 N Slappey Blvd, Albany, GA 31701",Albany,"Albany, Albany",-84.175900,31.588200,NaN,...,Dollar($),No,No,No,No,1,3.4,Orange,Average,36
94,17284158,Jimmie's Hot Dogs,216,Albany,"204 S Jackson St, Albany, GA 31701",Albany,"Albany, Albany",-84.153400,31.575100,NaN,...,Dollar($),No,No,No,No,1,3.9,Yellow,Good,160
297,17374552,Corkscrew Cafe,216,Gainesville,"51 W Main St, Dahlonega, GA 30533",Dahlonega,"Dahlonega, Gainesville",-83.985800,34.531800,NaN,...,Dollar($),No,No,No,No,3,3.9,Yellow,Good,209
328,17501439,Dovetail,216,Macon,"543 Cherry St, Macon, GA 31201",Macon,"Macon, Macon",-83.627979,32.836410,NaN,...,Dollar($),No,No,No,No,3,3.8,Yellow,Good,102
346,17606621,HI Lite Bar & Lounge,216,Miller,"109 N Broadway Ave, Miller, SD 57362",Miller,"Miller, Miller",-98.989100,44.515800,NaN,...,Dollar($),No,No,No,No,1,3.4,Orange,Average,11
368,17059060,Hillstone,216,Orlando,"215 South Orlando Avenue, Winter Park, FL 32789",Winter Park,"Winter Park, Orlando",-81.365260,28.596682,NaN,...,Dollar($),No,No,No,No,3,4.4,Green,Very Good,1158
418,17142698,Leonard's Bakery,216,Rest of Hawaii,"933 Kapahulu Ave, Honolulu, HI 96816",Kaimuki,"Kaimuki, Rest of Hawaii",-157.813432,21.284586,NaN,...,Dollar($),No,No,No,No,1,4.7,Dark Green,Excellent,707
455,17616465,Tybee Island Social Club,216,Savannah,"1311 Butler Ave, Tybee Island, GA 31328",Tybee Island,"Tybee Island, Savannah",-80.848297,31.995810,NaN,...,Dollar($),No,No,No,No,1,3.9,Yellow,Good,309

In [ ]:
df = df.explode('Cuisines')
print(df['Cuisines'].head(200))

0            French, Japanese, Desserts
1                              Japanese
2      Seafood, Asian, Filipino, Indian
3                       Japanese, Sushi
4                      Japanese, Korean
                     ...
195              Japanese, Steak, Sushi
196               Japanese, Sushi, Thai
197          Seafood, Steak, Vegetarian
198                               Steak
199                             Chinese
Name: Cuisines, Length: 200, dtype: object

In [ ]:
top20 = df['Cuisines'].value_counts().head(9551)
print(top20)

Cuisines
North Indian                          936
North Indian, Chinese                 511
Chinese                               354
Fast Food                             354
North Indian, Mughlai                 334
                                     ...
World Cuisine, Patisserie, Cafe         1
Burger, Izgara                          1
Desserts, B�_rek                        1
Restaurant Cafe, Turkish, Desserts      1
Restaurant Cafe, Desserts               1
Name: count, Length: 1825, dtype: int64

In [ ]:
print("Unique cuisines:", df['Cuisines'].nunique())

Unique cuisines: 1825

In [ ]:
counts = df['Cuisines'].value_counts().head(3)

print("\nCuisine counts:\n", counts)

Cuisine counts:
 Cuisines
North Indian             936
North Indian, Chinese    511
Chinese                  354
Name: count, dtype: int64

In [ ]:
percentage = (counts / len(df)) * 100
print(percentage)

Cuisines
North Indian             9.800021
North Indian, Chinese    5.350225
Chinese                  3.706418
Name: count, dtype: float64

In [ ]:
total_resturant=df['Restaurant ID'].nunique()
print(total_resturant)

9551

In [ ]:
percentage=(counts/total_resturant)*100
print(percentage)

Cuisines
North Indian             9.800021
North Indian, Chinese    5.350225
Chinese                  3.706418
Name: count, dtype: float64

# Task 2  Task: City Analysis

In [ ]:
city=df['City'].nunique()
print('City Unique counts: ', city)

City Unique counts:  141

In [ ]:
counts=df['City'].value_counts()
print(counts)

City
New Delhi         5473
Gurgaon           1118
Noida             1080
Faridabad          251
Ghaziabad           25
                  ...
Lakes Entrance       1
Mohali               1
Panchkula            1
Bandung              1
Randburg             1
Name: count, Length: 141, dtype: int64

In [ ]:
#weired_city=df[df['City'].str.contains('?')]
weird_cities = df[df['City'].str.contains('\?')]
print(weird_cities)

Empty DataFrame
Columns: [Restaurant ID, Restaurant Name, Country Code, City, Address, Locality, Locality Verbose, Longitude, Latitude, Cuisines, Average Cost for two, Currency, Has Table booking, Has Online delivery, Is delivering now, Switch to order menu, Price range, Aggregate rating, Rating color, Rating text, Votes]
Index: []

[0 rows x 21 columns]

In [ ]:
print(df['City'].unique())

['Makati City' 'Mandaluyong City' 'Pasay City' 'Pasig City' 'Quezon City'
 'San Juan City' 'Santa Rosa' 'Tagaytay City' 'Taguig City' 'Bras�_lia'
 'Rio de Janeiro' 'S��o Paulo' 'Albany' 'Armidale' 'Athens' 'Augusta'
 'Balingup' 'Beechworth' 'Boise' 'Cedar Rapids/Iowa City' 'Chatham-Kent'
 'Clatskanie' 'Cochrane' 'Columbus' 'Consort' 'Dalton' 'Davenport'
 'Des Moines' 'Dicky Beach' 'Dubuque' 'East Ballina' 'Fernley' 'Flaxton'
 'Forrest' 'Gainesville' 'Hepburn Springs' 'Huskisson' 'Inverloch'
 'Lakes Entrance' 'Lakeview' 'Lincoln' 'Lorn' 'Macedon' 'Macon' 'Mayfield'
 'Mc Millan' 'Middleton Beach' 'Miller' 'Monroe' 'Montville'
 'Ojo Caliente' 'Orlando' 'Palm Cove' 'Paynesville' 'Penola' 'Pensacola'
 'Phillip Island' 'Pocatello' 'Potrero' 'Princeton' 'Rest of Hawaii'
 'Savannah' 'Singapore' 'Sioux City' 'Tampa Bay' 'Tanunda' 'Trentham East'
 'Valdosta' 'Vernonia' 'Victor Harbor' 'Vineland Station' 'Waterloo'
 'Weirton' 'Winchester Bay' 'Yorkton' 'Abu Dhabi' 'Dubai' 'Sharjah' 'Agra'
 'Ahmedabad' 'Allahabad' 'Amritsar' 'Aurangabad' 'Bangalore' 'Bhopal'
 'Bhubaneshwar' 'Chandigarh' 'Chennai' 'Coimbatore' 'Dehradun' 'Faridabad'
 'Ghaziabad' 'Goa' 'Gurgaon' 'Guwahati' 'Hyderabad' 'Indore' 'Jaipur'
 'Kanpur' 'Kochi' 'Kolkata' 'Lucknow' 'Ludhiana' 'Mangalore' 'Mohali'
 'Mumbai' 'Mysore' 'Nagpur' 'Nashik' 'New Delhi' 'Noida' 'Panchkula'
 'Patna' 'Puducherry' 'Pune' 'Ranchi' 'Secunderabad' 'Surat' 'Vadodara'
 'Varanasi' 'Vizag' 'Bandung' 'Bogor' 'Jakarta' 'Tangerang' 'Auckland'
 'Wellington City' 'Birmingham' 'Edinburgh' 'London' 'Manchester' 'Doha'
 'Cape Town' 'Inner City' 'Johannesburg' 'Pretoria' 'Randburg' 'Sandton'
 'Colombo' 'Ankara' '��stanbul']

In [ ]:
weird = df[df['City'].apply(lambda x: not str(x).isascii())]
print(weird['City'].unique())

['Bras�_lia' 'S��o Paulo' '��stanbul']

In [ ]:
for city in weird['City'].unique():
    print(repr(city))

'Bras�_lia'
'S��o Paulo'
'��stanbul'

In [ ]:
df['City'] = df['City'].replace({
    'S��o Paulo': 'Sao Paulo',
    'Bras�_lia': 'Brasilia',
    '��stanbul': 'Istanbul'
})
print("Updated City names:" ,df['City'])

Updated City names: 0            Makati City
1            Makati City
2       Mandaluyong City
3       Mandaluyong City
4       Mandaluyong City
              ...
9546            Istanbul
9547            Istanbul
9548            Istanbul
9549            Istanbul
9550            Istanbul
Name: City, Length: 9551, dtype: object

# highest number of restaurants in the dataset

In [ ]:
city_count=df['City'].value_counts()
print("Highest number of restaurants in the dataset:",city_count)

Highest number of restaurants in the dataset: City
New Delhi         5473
Gurgaon           1118
Noida             1080
Faridabad          251
Ghaziabad           25
                  ...
Lakes Entrance       1
Mohali               1
Panchkula            1
Bandung              1
Randburg             1
Name: count, Length: 141, dtype: int64

In [ ]:
avg_city_count=df.groupby('City')['Aggregate rating'].mean()
print("Average rating for restaurants in each city :",avg_city_count)

Average rating for restaurants in each city : City
Abu Dhabi          4.300000
Agra               3.965000
Ahmedabad          4.161905
Albany             3.555000
Allahabad          3.395000
                     ...
Waterloo           3.650000
Weirton            3.900000
Wellington City    4.250000
Winchester Bay     3.200000
Yorkton            3.300000
Name: Aggregate rating, Length: 141, dtype: float64

In [ ]:
high_avg_city_count=avg_city_count.sort_values(ascending=False).head()
print("city with the highest average rating :",high_avg_city_count)

city with the highest average rating : City
Inner City          4.900000
Quezon City         4.800000
Makati City         4.650000
Pasig City          4.633333
Mandaluyong City    4.625000
Name: Aggregate rating, dtype: float64

# Task 3 Task: Price Range Distribution

In [ ]:
price_counts = df['Price range'].value_counts()

percentage = (price_counts / len(df)) * 100

print("Percentage of restaurants in each price range:")
print(percentage)

Percentage of restaurants in each price range:
Price range
1    46.529159
2    32.593446
3    14.741912
4     6.135483
Name: count, dtype: float64

# Task 4 Task: Online Delivery

In [ ]:
online=df['Has Online delivery'].value_counts()
percentage_online=(online/len(df))*100
print('Restaurants that offer online delivery')
print(percentage_online)

Restaurants that offer online delivery
Has Online delivery
No     74.337766
Yes    25.662234
Name: count, dtype: float64

In [ ]:
avg_rating=df.groupby('Has Online delivery')['Aggregate rating'].mean()
print('Average ratings of restaurants with and without online delivery')
print(avg_rating)

Average ratings of restaurants with and without online delivery
Has Online delivery
No     2.465296
Yes    3.248837
Name: Aggregate rating, dtype: float64

# Level 3

## Task 1 : Task: Restaurant Reviews

In [ ]:
print(df.columns)

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [ ]:
positive_reviews =df[df['Rating text'].isin(['Excellent', 'Very Good', 'Good'])]
print("Positive Reviews:")
print(positive_reviews['Rating text'].head())

Positive Reviews:
0    Excellent
1    Excellent
2    Very Good
3    Excellent
4    Excellent
Name: Rating text, dtype: object

In [ ]:
negative_reviews =df[df['Rating text'].isin(['Average', 'Not rated', 'Poor'])]
print("Negative Reviews:")
print(negative_reviews['Rating text'].head())

Negative Reviews:
22      Average
26      Average
27      Average
30    Not rated
32      Average
Name: Rating text, dtype: object

In [ ]:
df['Review Length'] = df['Rating text'].astype(str).apply(len)
correlation = df[['Review Length', 'Aggregate rating']].corr()

print("Correlation between Review Length and Rating:")
print(correlation)

Correlation between Review Length and Rating:
                  Review Length  Aggregate rating
Review Length          1.000000         -0.478885
Aggregate rating      -0.478885          1.000000

# Task 2-Task: Votes Analysis

In [ ]:
df['Restaurant Name'].value_counts()

Restaurant Name
Cafe Coffee Day             83
Domino's Pizza              79
Subway                      63
Green Chick Chop            51
McDonald's                  48
                            ..
Naml۱ Gurme                  1
Ceviz A��ac۱                 1
Huqqa                        1
A���k Kahve                  1
Walter's Coffee Roastery     1
Name: count, Length: 7446, dtype: int64

In [ ]:
df['Restaurant Name'].nunique()

7446

In [ ]:
weird = df[df['Restaurant Name'].apply(lambda x: not str(x).isascii())]
print(weird['Restaurant Name'].unique())

['Caf�� Daniel Briand' 'Pizza �� Bessa' 'Sandubas Caf��' 'Tayp��'
 'Manzu��' 'Braseiro da G��vea' 'Zaz�� Bistr�� Tropical' 'Fil�� de Ouro'
 'Apraz�_vel' 'Terra�_o It��lia' 'Divino Fog��o' 'Esquina Mocot�_'
 'Cev�_che Tapas Bar & Restaurant' 'Caf�� Tu Tu Tango'
 "Hollerbach's Willow Tree Caf��" 'MoMo Caf�� - Courtyard By Marriott'
 'Caf�� Bogchi' 'Caf�� Kitchen' 'Gallery Caf�� - Hyatt Place'
 "Longitude 77��03' Bar - Le Meridien Gurgaon" 'bu��no' 'Queens Caf��'
 'Caf�� Gramophone' 'M Cr��me' 'West��ross' "Chawla's�_" 'Caf�� Burger BC'
 'The Basement Caf��' 'Caf�� Riverrun' 'Con�_u'
 'Sahib��s Barbeque by Ohri��s' 'Hobnob Gourmet Caf��bar'
 'Chemistry Caf��' 'NESCAF� Illusions' 'It��s Sinful' 'Caf�� MRP'
 'D�_ner Grill' 'Caf�� Healthilicious' 'LaBont��' 'Chhalava - �__Lava'
 'The Walled City - Caf�� & Lounge' 'Bon App��tit'
 'Cottage Caf�� by Smoothie factory' 'Dialogue Lounge & Caf��'
 "Ping's Caf�� Orient" 'Delhite P��tisserie' 'Arabian & Turkish Caf��'
 'Die B�_ckerei' 'High Street Caf��' 'The Junkyard Caf��'
 'AMPM Caf�� & Bar' 'Caf�� Foreground' 'Rosart�� Chocolate'
 'Caf�� Befikre' 'Caf�� 101' 'Tin Town Caf��' 'Superstar Caf��'
 'H�_agen-Dazs' 'The Fashion Street Caf��' 'Hearken Caf��'
 'Remember Me Caf��' '4 Barrels Caf�� & Lounge'
 'Caf�� Knosh - The Leela Ambience Convention Hotel' 'The Village Caf��'
 'Phonebooth Caf��' 'Caf�� Doo Ghoont' 'TBH ��� To Be Healthy'
 'They�_����' 'Caff�� La Poya' 'More Than Caf��' 'Elixir Health Caf��'
 '#Urban Caf��' 'The Chickmunks Caf��' 'KBC�_'
 "Chef's Basket Pop Up Caf��" 'Saut��ed Stories'
 'Freshco - The Health Caf��' 'Eden Noodles Cafe �__·�_��_��_��'
 'Grand Caf�� & Beach' 'Hattena Hatay  Sofras۱' 'Masaba��۱ Kebap�_۱s۱'
 'Me��hur Tavac۱ Recep Usta' '�ukura��a Sofras۱'
 'Me��hur �_z�_elik Aspava' 'Y۱ld۱z Aspava' 'Masaba��۱' 'D�_vero��lu'
 'Pizza ��l Forno' 'Emirgan S�_ti��' 'Leman K�_lt�_r' 'Dem Karak�_y'
 'Karak�_y G�_ll�_o��lu' 'Naml۱ Gurme' 'Ceviz A��ac۱' 'A���k Kahve']

In [ ]:
for Restaurant_Name in weird['Restaurant Name'].unique():
    print(repr(Restaurant_Name))

'Caf�� Daniel Briand'
'Pizza �� Bessa'
'Sandubas Caf��'
'Tayp��'
'Manzu��'
'Braseiro da G��vea'
'Zaz�� Bistr�� Tropical'
'Fil�� de Ouro'
'Apraz�_vel'
'Terra�_o It��lia'
'Divino Fog��o'
'Esquina Mocot�_'
'Cev�_che Tapas Bar & Restaurant'
'Caf�� Tu Tu Tango'
"Hollerbach's Willow Tree Caf��"
'MoMo Caf�� - Courtyard By Marriott'
'Caf�� Bogchi'
'Caf�� Kitchen'
'Gallery Caf�� - Hyatt Place'
"Longitude 77��03' Bar - Le Meridien Gurgaon"
'bu��no'
'Queens Caf��'
'Caf�� Gramophone'
'M Cr��me'
'West��ross'
"Chawla's�_"
'Caf�� Burger BC'
'The Basement Caf��'
'Caf�� Riverrun'
'Con�_u'
'Sahib��s Barbeque by Ohri��s'
'Hobnob Gourmet Caf��bar'
'Chemistry Caf��'
'NESCAF� Illusions'
'It��s Sinful'
'Caf�� MRP'
'D�_ner Grill'
'Caf�� Healthilicious'
'LaBont��'
'Chhalava - �__Lava'
'The Walled City - Caf�� & Lounge'
'Bon App��tit'
'Cottage Caf�� by Smoothie factory'
'Dialogue Lounge & Caf��'
"Ping's Caf�� Orient"
'Delhite P��tisserie'
'Arabian & Turkish Caf��'
'Die B�_ckerei'
'High Street Caf��'
'The Junkyard Caf��'
'AMPM Caf�� & Bar'
'Caf�� Foreground'
'Rosart�� Chocolate'
'Caf�� Befikre'
'Caf�� 101'
'Tin Town Caf��'
'Superstar Caf��'
'H�_agen-Dazs'
'The Fashion Street Caf��'
'Hearken Caf��'
'Remember Me Caf��'
'4 Barrels Caf�� & Lounge'
'Caf�� Knosh - The Leela Ambience Convention Hotel'
'The Village Caf��'
'Phonebooth Caf��'
'Caf�� Doo Ghoont'
'TBH ��� To Be Healthy'
'They�_����'
'Caff�� La Poya'
'More Than Caf��'
'Elixir Health Caf��'
'#Urban Caf��'
'The Chickmunks Caf��'
'KBC�_'
"Chef's Basket Pop Up Caf��"
'Saut��ed Stories'
'Freshco - The Health Caf��'
'Eden Noodles Cafe �__·�_��_��_��'
'Grand Caf�� & Beach'
'Hattena Hatay  Sofras۱'
'Masaba��۱ Kebap�_۱s۱'
'Me��hur Tavac۱ Recep Usta'
'�ukura��a Sofras۱'
'Me��hur �_z�_elik Aspava'
'Y۱ld۱z Aspava'
'Masaba��۱'
'D�_vero��lu'
'Pizza ��l Forno'
'Emirgan S�_ti��'
'Leman K�_lt�_r'
'Dem Karak�_y'
'Karak�_y G�_ll�_o��lu'
'Naml۱ Gurme'
'Ceviz A��ac۱'
'A���k Kahve'

In [ ]:
weird_resturant = df[df['Restaurant Name'].apply(lambda x: not str(x).isascii())]
print(weird_resturant['Restaurant Name'].unique(),'\n')
print('Number of weird_resturant :',len(weird_resturant))

['Caf�� Daniel Briand' 'Pizza �� Bessa' 'Sandubas Caf��' 'Tayp��'
 'Manzu��' 'Braseiro da G��vea' 'Zaz�� Bistr�� Tropical' 'Fil�� de Ouro'
 'Apraz�_vel' 'Terra�_o It��lia' 'Divino Fog��o' 'Esquina Mocot�_'
 'Cev�_che Tapas Bar & Restaurant' 'Caf�� Tu Tu Tango'
 "Hollerbach's Willow Tree Caf��" 'MoMo Caf�� - Courtyard By Marriott'
 'Caf�� Bogchi' 'Caf�� Kitchen' 'Gallery Caf�� - Hyatt Place'
 "Longitude 77��03' Bar - Le Meridien Gurgaon" 'bu��no' 'Queens Caf��'
 'Caf�� Gramophone' 'M Cr��me' 'West��ross' "Chawla's�_" 'Caf�� Burger BC'
 'The Basement Caf��' 'Caf�� Riverrun' 'Con�_u'
 'Sahib��s Barbeque by Ohri��s' 'Hobnob Gourmet Caf��bar'
 'Chemistry Caf��' 'NESCAF� Illusions' 'It��s Sinful' 'Caf�� MRP'
 'D�_ner Grill' 'Caf�� Healthilicious' 'LaBont��' 'Chhalava - �__Lava'
 'The Walled City - Caf�� & Lounge' 'Bon App��tit'
 'Cottage Caf�� by Smoothie factory' 'Dialogue Lounge & Caf��'
 "Ping's Caf�� Orient" 'Delhite P��tisserie' 'Arabian & Turkish Caf��'
 'Die B�_ckerei' 'High Street Caf��' 'The Junkyard Caf��'
 'AMPM Caf�� & Bar' 'Caf�� Foreground' 'Rosart�� Chocolate'
 'Caf�� Befikre' 'Caf�� 101' 'Tin Town Caf��' 'Superstar Caf��'
 'H�_agen-Dazs' 'The Fashion Street Caf��' 'Hearken Caf��'
 'Remember Me Caf��' '4 Barrels Caf�� & Lounge'
 'Caf�� Knosh - The Leela Ambience Convention Hotel' 'The Village Caf��'
 'Phonebooth Caf��' 'Caf�� Doo Ghoont' 'TBH ��� To Be Healthy'
 'They�_����' 'Caff�� La Poya' 'More Than Caf��' 'Elixir Health Caf��'
 '#Urban Caf��' 'The Chickmunks Caf��' 'KBC�_'
 "Chef's Basket Pop Up Caf��" 'Saut��ed Stories'
 'Freshco - The Health Caf��' 'Eden Noodles Cafe �__·�_��_��_��'
 'Grand Caf�� & Beach' 'Hattena Hatay  Sofras۱' 'Masaba��۱ Kebap�_۱s۱'
 'Me��hur Tavac۱ Recep Usta' '�ukura��a Sofras۱'
 'Me��hur �_z�_elik Aspava' 'Y۱ld۱z Aspava' 'Masaba��۱' 'D�_vero��lu'
 'Pizza ��l Forno' 'Emirgan S�_ti��' 'Leman K�_lt�_r' 'Dem Karak�_y'
 'Karak�_y G�_ll�_o��lu' 'Naml۱ Gurme' 'Ceviz A��ac۱' 'A���k Kahve']

Number of weird_resturant : 106

# Task 3-Task: Price Range vs. Online Delivery and Table Booking

In [ ]:
online = df.groupby('Price range')['Has Online delivery'].value_counts()
print(online)

Price range  Has Online delivery
1            No                     3743
             Yes                     701
2            No                     1827
             Yes                    1286
3            No                      997
             Yes                     411
4            No                      533
             Yes                      53
Name: count, dtype: int64

In [ ]:
online_percent = df.groupby('Price range')['Has Online delivery'].value_counts(normalize=True) * 100
print(online_percent)

Price range  Has Online delivery
1            No                     84.225923
             Yes                    15.774077
2            No                     58.689367
             Yes                    41.310633
3            No                     70.809659
             Yes                    29.190341
4            No                     90.955631
             Yes                     9.044369
Name: proportion, dtype: float64

In [ ]:
table_booking = df.groupby('Price range')['Has Table booking'].value_counts()
print(table_booking)

Price range  Has Table booking
1            No                   4443
             Yes                     1
2            No                   2874
             Yes                   239
3            No                    764
             Yes                   644
4            No                    312
             Yes                   274
Name: count, dtype: int64

In [ ]:
table_booking_percent= df.groupby('Price range')['Has Table booking'].value_counts(normalize=True)*100
print(table_booking_percent)

Price range  Has Table booking
1            No                   99.977498
             Yes                   0.022502
2            No                   92.322518
             Yes                   7.677482
3            No                   54.261364
             Yes                  45.738636
4            No                   53.242321
             Yes                  46.757679
Name: proportion, dtype: float64